<?php

namespace ExclusiveBooks\DemoAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobConfigDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobConfigDataRepository extends EntityRepository
{
    
}
