<?php

namespace ExclusiveBooks\DemoAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobDescriptionRepository extends EntityRepository
{
}
