<?php

namespace ExclusiveBooks\DemoAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRepository extends EntityRepository
{
 public function findAllActive()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ExclusiveBooksDemoAppBundle:Server p where p.serverStatus <> :status'
            )
            ->setParameter('status', 'D')
            ->getResult();
    }
}
